### ISSUE TITLE
Documentation not up to date?

### ISSUE THREAD

**Issue by teejays** [ufoscout/go-up#12]
Hi - I like the idea behind the project and was trying to use it in one of my projects. It seems like the documentation needs updating: 
1) the package needs to be imported with an explicit name "go_up"
2) No function .build() but there is Build()

**Comment by ufoscout** [comment]
Hi @teejays 

Thanks, I checked the documentation and fixed all the ".build()" typos. 

About your point number 1:

> the package needs to be imported with an explicit name "go_up"

could you please be more specific? I don't get exactly what is the issue. The default package name is "go_up" so it shouldn't be required. Are you using version 0.5.0?

**Comment by teejays** [comment]
Thanks. Yes, the second point makes sense. I got a little confused as I follow the standards of the package name exactly matching the project folder name.

In the documentation, can you make sure that the sample code uses go_up.NewGoUp(..) vs. NewGoUp(...).
