### ISSUE TITLE
Viper dependency

### ISSUE THREAD

**Issue by ignaci0** [ufoscout/go-up#13]
Hi,

First of all, nice library!

I've found the following issue while trying to use it from a docker image:

```src/github.com/ufoscout/go-up/examples/viper/main.go:6:2: cannot find package "github.com/spf13/viper" in any of:
        /usr/local/go/src/github.com/spf13/viper (from $GOROOT)
        /go/src/github.com/spf13/viper (from $GOPATH)
```

It seems the example is trying to force getting the viper module and I'm using this one because I don't want any viper ;)

Do you mind skipping the build process for the examples or removing them for good?

Thanks

**Comment by ufoscout** [comment]
Hi @ignaci0 
go-up does not depend on viper.

What do you mean exactly by:
> Do you mind skipping the build process for the examples or removing them for good?

If you import go-up as a dependency in your go.mod file the examples should be automatically ignored.

**Comment by ignaci0** [comment]
Hi @ufoscout,

I use docker for builds, while building in docker (using a clean image every time), I get the following error:

```src/github.com/ufoscout/go-up/examples/viper/main.go:6:2: cannot find package "github.com/spf13/viper" in any of:
        /usr/local/go/src/github.com/spf13/viper (from $GOROOT)
        /go/src/github.com/spf13/viper (from $GOPATH)
ERROR: Service 'testapp' failed to build: The command '/bin/sh -c go get -d -v ./...' returned a non-zero code: 1
```

By any reason, the viper example is being built even though I'm importing the library as a dependency for my testapp.

What I did for the time being is to fork the code and to delete the examples. Maybe there are better options out there to handle "examples".

**Comment by ufoscout** [comment]
@ignaci0 
do you use go modules?

**Comment by ignaci0** [comment]
Hi,

I tested it using the following:
```
module testapp

go 1.13

require github.com/ufoscout/go-up v0.6.0 // indirect
```

Same result

**Comment by ufoscout** [comment]
Ok, got it. The reasoning behind Go modules is sometimes obscure to me.

I moved the examples to a separate repository; this should fix your issue.

@ignaci0 please try version `v0.6.1` and let me know.

**Comment by ignaci0** [comment]
With version 0.6.1 is working fine!

Thanks @ufoscout
